### ISSUE TITLE
ControllerUnpublishVolume logic error

### ISSUE THREAD

**Issue by zuzzas** [flant/yandex-csi-driver#6]
Should stick closer to the spec and query attachment information directly from the Disk object.

**Comment by Negashev** [comment]
Yes, I still cannot fully understand, but it seems if I delete the node named `example-1` from the Kubernetes cluster, with the disk mounted, and create a new node named `example-1`.
CSI-controller will try to endlessly detach the disk from the new `example-1` VM

(Play with rancher (RKE) and docker-machine-driver-yandex)
```
I1118 23:19:18.559779       1 connection.go:185] GRPC response: {}
I1118 23:19:18.560826       1 connection.go:186] GRPC error: rpc error: code = Internal desc = rpc error: code = InvalidArgument desc = Request validation error: Can't find disk in instance "fhmddkkixxxxxxxxxxxx"
I1118 23:19:18.560864       1 csi_handler.go:575] Saving detach error to "csi-ad48a2c982730fae5c871dxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
I1118 23:19:18.593983       1 csi_handler.go:586] Saved detach error to "csi-ad48a2c982730fae5c871dxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
I1118 23:19:18.594019       1 csi_handler.go:219] Error processing "csi-ad48a2c982730fae5c871dxxxxxxxxxxxxxxxxxxxxxxxxxxxxx": failed to detach: rpc error: code = Internal desc = rpc error: code = InvalidArgument desc = Request validation error: Can't find disk in instance "fhmddkkixxxxxxxxxxxx"
```

**Comment by Negashev** [comment]
https://github.com/flant/yandex-csi-driver/blob/2c3dd62e8b27ee1ae3ad6ec95c4e2e235d9756e5/deploy/1.17/csi-controller.yaml#L58

it seems to work better with flant/yandex-csi-plugin `v0.9.10`

**Comment by zuzzas** [comment]
I've actually [fixed](https://github.com/flant/yandex-csi-driver/commit/6660249252f03f205e17126724f9b2d338cf202f) this problem some time ago. I've got some changes to the repository's release process that I'll roll out next week.

There'll be git tags and accordingly tagged Docker images. Apologies for the confusion.
